### PR TITLE
fix: export typescript types

### PR DESCRIPTION
**Pull request by stefan-karlsson**
this commit makes sure that the package exports exposes typescript types

### CODE REVIEW

**Review by frehner — CHANGES_REQUESTED** [review]
Thanks! The content here looks great; one additional request, if you don't mind - can you move the `types` field to be the first in the object instead of the last? Thanks!

**Review by joeldenning — COMMENTED** [review]
This looks fine, but might need to be a breaking major change? Adding typescript types might break things for anyone using types from DefinitelyTyped or elsewhere. Generally speaking, whenever I see a change to the `exports` or `types` properties in package.json, I wonder whether it should be a breaking change.

**Comment by frehner** [comment]
I personally feel it's ok as a patch, but it's up to you.

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-layout/releases/tag/v2.2.0

**Pull request merged**
