### PR TITLE
allow class attribute on application node

### PR DESCRIPTION
**Pull request by jamesarosen**
This PR replaces #154, adding unit tests for the class name.

I changed the commit author to myself so I could sign the commit, but kept @MarcusResell in the `co-authored-by` since he did all the hard work!

### CODE REVIEW

**Review by thejayhaykid — APPROVED** [review]

**Comment by AndrewSGould** [comment]
Any progress on this?

Additionally, it looks like we may want to consider having this operate similarly when using `<Parcel>` elements

**Comment by thejayhaykid** [comment]
@AndrewSGould I will do this when I get the time so that the PR can at least be available

**Review by AndrewSGould — APPROVED** [review]

**Review by joeldenning — APPROVED** [review]
This looks good, thanks

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-layout/releases/tag/v2.2.0

**Comment by joeldenning** [comment]
Documented in https://github.com/single-spa/single-spa.js.org/pull/586

**Pull request merged**
